### ISSUE TITLE
Prettier errors when template path is not found

### ISSUE THREAD

**Issue by binyamin** [sindresorhus/gulp-nunjucks#39]
Currently, when a template `extends` a non-existent layout, the plugin throws an error which is long and ugly. It also logs a very large object which looks like the gulp pipeline.

**Comment by sindresorhus** [comment]
This issue has been fixed! 🎉

The problem was that Nunjucks template errors (like missing extends/includes) contained very verbose stack traces and internal implementation details that weren't helpful for debugging.

## What's Changed

The plugin now provides much cleaner error messages:

**Before:**
```
Template render error: (unknown path)
  Error: template not found: layout.njk
    at Object._prettifyError (/node_modules/nunjucks/src/lib.js:32:11)
    at /node_modules/nunjucks/src/environment.js:464:19
    at eval (eval at _compile (/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:10:11)
    [... many more lines of internal stack trace ...]
```

**After:**
```
Template not found: layout.njk
```

## Examples

These template errors now show clean, actionable messages:

- `{% extends "missing-layout.njk" %}` → `Template not found: missing-layout.njk`
- `{% include "missing-partial.njk" %}` → `Template not found: missing-partial.njk`

The error still includes the file path where the error occurred (via Gulp's standard error handling), but without the verbose internal Nunjucks stack traces.

This improvement will be available in the next release!
